### ISSUE TITLE
Change network magic bits

### ISSUE THREAD

**Issue by sickpig** [bitcoin-cored/bitcoin-cored#24]
@corelyone

Bitcoin-cored is currently using the same network magic bits as Bitcoin Cash clients are, see: 

https://github.com/bitcoin-cored/bitcoin-cored/blob/master/src/chainparams.cpp#L179

what about adopting a new set of magic bits so that you want try to connect to Bitcoin Cash client?

**Comment by clashicly** [comment]
ACK. They were scheduled to be updated on the last release. It didn't make it.
They will be added to next release.

**Comment by clashicly** [comment]
resolved in https://github.com/title-network/title-network/commit/d95d5a2419a38e3259d2f421d318b3b148f08368#diff-64cbe1ad5465e13bc59ee8bb6f3de2e7
